include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    use_build_context_synchronously: ignore 
  plugins: 
    - custom_lint
  exclude: 
    - lib/language/generated/**

linter:
  rules:
