name: picacg
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  cupertino_icons: ^1.0.8
  rust_lib_picacg:
    path: rust_builder
  flutter_rust_bridge: 2.10.0
  freezed_annotation: ^3.0.0
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  go_router: ^15.2.0
  responsive_framework: ^1.5.1
  lottie: ^3.3.1
  path_provider: ^2.1.5
  flutter_svg: ^2.1.0
  carousel_slider: ^5.1.1
  cached_network_image: ^3.4.1
  skeletonizer: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  freezed: ^3.0.6
  custom_lint: ^0.7.5
  build_runner: ^2.5.0
  flutter_lints: ^6.0.0
  riverpod_generator: ^2.6.5
  riverpod_lint: ^2.6.5
  intl_utils: ^2.8.10

flutter:
  generate: true
  uses-material-design: true
  assets:
    - lib/assets/lotties/
    - lib/assets/svg/
    - lib/assets/images/

flutter_intl:
  enabled: true
  class_name: Language
  main_locale: zh
  arb_dir: lib/language/arb
  output_dir: lib/language/generated