name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  FLUTTER_VERSION: '3.32.2'

jobs:
  fmt:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: stable
          components: 'clippy, rustfmt'

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'zulu'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: stable

      - name: Run Flutter Pub Get
        run: flutter pub get

      - name: Check Flutter Code
        run: dart format --set-exit-if-changed lib test

      - name: Run Generate Language
        run: flutter pub run intl_utils:generate

      - name: Generate Flutter Code
        run: |
          cargo install flutter_rust_bridge_codegen
          flutter_rust_bridge_codegen generate

      - name: Run Fmt
        working-directory: rust
        run: cargo fmt --all -- --check

      - name: Run Clippy
        working-directory: rust
        run: cargo clippy --all-targets --all-features -- -D warnings
      
      - name: Run Tests
        working-directory: rust
        run: cargo test -- --test-threads=1

      - name: Run Flutter Analysis
        run: flutter analyze lib
